RunGroupWebApp/ViewModels/DashboardViewModel.cs
using RunGroupWebApp.Models;

namespace RunGroupWebApp.ViewModels
{
    public class DashboardViewModel
    {
        public List<Races> Races { get; set; }
        public List<Club> Clubs { get; set; }
    }
}

RunGroupWebApp/Controllers/ClubController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RunGroupWebApp.Data;
using RunGroupWebApp.Interfaces;
using RunGroupWebApp.Models;
using RunGroupWebApp.Repository;
using RunGroupWebApp.ViewModels;

namespace RunGroupWebApp.Controllers
{
    public class ClubController : Controller
    {

        private readonly IClubRepository _clubRepository;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public ClubController(IClubRepository clubRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {
            _clubRepository = clubRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor; 
        }
        public async Task<IActionResult> Index()//ccc Controller
        {
            IEnumerable<Club> clubs = await _clubRepository.GetAll();//mmm Model
            return View(clubs);//vvv view
        }


        public async Task<IActionResult> Detail(int id)
        {
            Club club = await _clubRepository.GetByIdAsync(id);
            return View(club);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var curUserId = HttpContext.User.GetUserId();
            var createClubViewModel = new CreateClubViewModel { AppUserId = curUserId };
            return View(createClubViewModel);
        }

       
        [HttpPost]
        public async Task<IActionResult> Create(CreateClubViewModel clubVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(clubVM.Image);


                var club = new Club
                {
                    Title = clubVM.Title,
                    Description = clubVM.Description,
                    Image = result.Url.ToString(),
                    AppUserId=clubVM.AppUserId,
                    Address = new Address
                    {
                        Street = clubVM.Address.Street,
                        City = clubVM.Address.City,
                        State = clubVM.Address.State
                    }
                };

                _clubRepository.Add(club);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Photo upload Failed");
            }
            return View(clubVM);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var club = await _clubRepository.GetByIdAsync(id);
            if(club == null)return View("Error");
            var clubVM = new EditClubViewModel
            {
                Title = club.Title,
                Description = club.Description,
                AddressId = club.AddressId,
                Address = club.Address,
                URL = club.Image.ToString(),
                ClubCategory = club.clubCategory
            };
            return View(clubVM);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditClubViewModel clubVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit club");
                return View("Edit", clubVM);
            }

            var userClub = await _clubRepository.GetByIdAsyncNoTracking(id);

            if (userClub != null)
            {
                try
                {
                    await _photoService.DeletePhotoAsync(userClub.Image);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"Could not delete photo  Error = {ex}");
                    return View(clubVM);
                }

                var photoResult = await _photoService.AddPhotoAsync(clubVM.Image);

                //if (photoResult.Error != null)
                //{
                //    ModelState.AddModelError("Image", "Photo upload failed");
                //    return View(clubVM);
                //}

                //if (!string.IsNullOrEmpty(userClub.Image))
                //{
                //var photoResults = _photoService.DeletePhotoAsync(userClub.Image);
                //}

                var club = new Club
                {
                    Id = id,
                    Title = clubVM.Title,
                    Description = clubVM.Description,
                    Image = photoResult.Url.ToString(),
                    AddressId = clubVM.AddressId,
                    Address = clubVM.Address,
                };

                _clubRepository.Update(club);

                return RedirectToAction("Index");
            }
            else
            {
                return View(clubVM); 
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            var clubDetails = await _clubRepository.GetByIdAsync(id);
            if (clubDetails == null) return View("Error");
            return View(clubDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteRace(int id)
        {
            var clubDetails = await _clubRepository.GetByIdAsync(id);
            if (clubDetails == null) return View("Error");
            _clubRepository.Delete(clubDetails);
            return RedirectToAction("Index");
        }
    }
}

RunGroupWebApp/Controllers/DashboardController.cs
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Mvc;
using RunGroupWebApp.Interfaces;
using RunGroupWebApp.Models;
using RunGroupWebApp.ViewModels;

namespace RunGroupWebApp.Controllers
{
    public class DashboardController : Controller
    {
       private readonly IDashboardRepository _dashboardRespository;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public DashboardController(IDashboardRepository dashboardRespository, IPhotoService photoService,IHttpContextAccessor httpContextAccessor)
        {
            _dashboardRespository = dashboardRespository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }
        private void MapUserEdit(AppUser user, EditUserDashboardViewModel editVM, ImageUploadResult photoResult)
        {
            user.Id = editVM.Id;
            user.Pace = editVM.Pace;
            user.Mileage = editVM.Mileage;
            user.ProfileImageUrl = photoResult.Url.ToString();
            user.City = editVM.City;
            user.State = editVM.State;
        }

        public async Task<IActionResult> Index()
        {
            var userRaces = await _dashboardRespository.GetAllUserRaces();
            var userClubs = await _dashboardRespository.GetAllUserClubs();
            var dashboardViewModel = new DashboardViewModel()
            {
                Races = userRaces,
                Clubs = userClubs
            };
            return View(dashboardViewModel);
        }


        public async Task<IActionResult> EditUserProfile()
        {
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var user = await _dashboardRespository.GetUserById(curUserId);
            if (user == null)
            {
                return View("Error");
            }
            var editUserViewModel = new EditUserDashboardViewModel()
            {
                Id = curUserId,
                Pace = user.Pace,
                Mileage = user.Mileage,
                ProfileImageUrl = user.ProfileImageUrl,
                City = user.City,
                State = user.State
            };
            return View(editUserViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> EditUserProfile(EditUserDashboardViewModel editVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit profile");
                return View("EditUserProfile", editVM);
            }

            AppUser user = await _dashboardRespository.GetByIdNoTracking(editVM.Id);

            if (user.ProfileImageUrl == "" || user.ProfileImageUrl == null)
            {

                var photoResult = await _photoService.AddPhotoAsync(editVM.Image);

                MapUserEdit(user, editVM, photoResult);

                _dashboardRespository.Update(user);

                return RedirectToAction("Index");
            }
            else
            {
                try
                {
                    await _photoService.DeletePhotoAsync(user.ProfileImageUrl);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(editVM);
                }
                var photoResult = await _photoService.AddPhotoAsync(editVM.Image);

                MapUserEdit(user, editVM, photoResult);

                _dashboardRespository.Update(user);

                return RedirectToAction("Index");
            }
        }

    }
}

RunGroupWebApp/Controllers/RaceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RunGroupWebApp.Data;
using RunGroupWebApp.Interfaces;
using RunGroupWebApp.Models;
using RunGroupWebApp.Repository;
using RunGroupWebApp.Services;
using RunGroupWebApp.ViewModels;

namespace RunGroupWebApp.Controllers
{
    public class RaceController : Controller
    {
        private readonly IRaceRepository _raceRepository;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public RaceController(IRaceRepository raceRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {
            _raceRepository = raceRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor; 
        }
        public async Task<IActionResult> Index()//ccc Controller
        {
            IEnumerable<Races> races = await _raceRepository.GetAll();//mmm Model
            return View(races);//vvv view
        }


        public async Task<IActionResult> Detail(int id)
        {
            Races races = await _raceRepository.GetByIdAsync(id);
            return View(races);
        }
        //[HttpGet]
        //public IActionResult Create()
        //{
        //    var curUserID = _httpContextAccessor.HttpContext?.User.GetUserId();
        //    var createRaceViewModel = new CreateRaceViewModel { AppUserId = curUserID };
        //    return View(createRaceViewModel);
        //}

        //[HttpPost]
        //public async Task<IActionResult> Create(CreateRaceViewModel raceVM)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var result = await _photoService.AddPhotoAsync(raceVM.Image);


        //        var race = new Races
        //        {
        //            Title = raceVM.Title,
        //            Description = raceVM.Description,
        //            Image = result.Url.ToString(),
        //            AppUserId= raceVM.AppUserId,
        //            Address = new Address
        //            {
        //                Street = raceVM.Address.Street,
        //                City = raceVM.Address.City,
        //                State = raceVM.Address.State
        //            }
        //        };

        //        _raceRepository.Add(race);
        //        return RedirectToAction("Index");
        //    }
        //    else
        //    {
        //        ModelState.AddModelError("", "Photo upload Failed");
        //    }
        //    return View(raceVM);
        //}

        [HttpGet]
        public IActionResult Create()
        {
            var curUserId = HttpContext.User.GetUserId();
            var createRaceViewModel = new CreateRaceViewModel { AppUserId = curUserId };
            return View(createRaceViewModel);
        }


        [HttpPost]
        public async Task<IActionResult> Create(CreateRaceViewModel raceVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(raceVM.Image);


                var race = new Races
                {
                    Title = raceVM.Title,
                    Description = raceVM.Description,
                    Image = result.Url.ToString(),
                    AppUserId = raceVM.AppUserId,
                    Address = new Address
                    {
                        Street = raceVM.Address.Street,
                        City = raceVM.Address.City,
                        State = raceVM.Address.State
                    }
                };

                _raceRepository.Add(race);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Photo upload Failed");
            }
            return View(raceVM);
        }


        public async Task<IActionResult> Edit(int id)
        {
            var race = await _raceRepository.GetByIdAsync(id);
            if(race == null)return View("Error");
            var raceVM = new EditRaceViewModel
            {
                Title = race.Title,
                Description = race.Description,
                AddressId = race.AddressId,
                Address = race.Address,
                URL = race.Image.ToString(),
                RaceCategory = race.RaceCategory
            };
            return View(raceVM);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditRaceViewModel raceVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit club");
                return View("Edit", raceVM);
            }

            var userClub = await _raceRepository.GetByIdAsyncNoTracking(id);

            if (userClub != null)
            {
                try
                {
                    await _photoService.DeletePhotoAsync(userClub.Image);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"Could not delete photo and error code is : {ex}");
                    return View(raceVM);
                }

                var photoResult = await _photoService.AddPhotoAsync(raceVM.Image);

                //if (photoResult.Error != null)
                //{
                //    ModelState.AddModelError("Image", "Photo upload failed");
                //    return View(clubVM);
                //}

                //if (!string.IsNullOrEmpty(userClub.Image))
                //{
                //var photoResults = _photoService.DeletePhotoAsync(userClub.Image);
                //}

                var races = new Races
                {
                    Id = id,
                    Title = raceVM.Title,
                    Description = raceVM.Description,
                    Image = photoResult.Url.ToString(),
                    AddressId = raceVM.AddressId,
                    Address = raceVM.Address,
                };

                _raceRepository.Update(races);

                return RedirectToAction("Index");
            }
            else
            {
                return View(raceVM); 
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            var raceDetails = await _raceRepository.GetByIdAsync(id);
            if (raceDetails == null) return View("Error");
            return View(raceDetails);
        }
        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteRace(int id)
        {
            var raceDetails = await _raceRepository.GetByIdAsync(id);
            if (raceDetails == null) return View("Error");
            _raceRepository.Delete(raceDetails);
            return RedirectToAction("Index");
        }
    }
}

RunGroupWebApp/Views/Dashboard/EditUserProfile.cshtml
@using RunGroupWebApp.ViewModels;
@model EditUserDashboardViewModel


<form method="post" asp-action="EditUserProfile" enctype="multipart/form-data">
    <input type="hidden" id="Id" name="Id" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Pace">Pace</label>
        <input asp-for="Pace" class="form-control" placeholder="Pace">
        <span asp-validation-for="Pace" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Mileage">Mileage</label>
        <input asp-for="Mileage" class="form-control" placeholder="Mileage">
        <span asp-validation-for="Mileage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="City">City</label>
        <input asp-for="City" class="form-control" placeholder="City">
        <span asp-validation-for="City" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="State">State</label>
        <input asp-for="State" class="form-control" placeholder="State">
        <span asp-validation-for="State" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image">Profile Image</label>
        <input asp-for="Image" type="file" class="form-control" placeholder="Image">
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

RunGroupWebApp/Views/Dashboard/Index.cshtml
﻿@using Microsoft.AspNetCore.Identity
@using RunGroupWebApp.ViewModels;
@inject SignInManager<AppUser> SignInManager
@model DashboardViewModel

<h1 class="display-4 fw-normal">User Dashboard</h1>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Club" asp-action="Create">Create Club</a>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Race" asp-action="Create">Create Race</a>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Dashboard" asp-action="EditUserProfile">Edit User Profile</a>
<div class="album py-5 bg-light">
    <div class="container">
        <h2 class="display-4 fw-normal">Your races</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            @foreach (var item in Model.Races)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.Image" width="100%" height="225" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Club" asp-action="Detail" asp-route-id="@item.Id"
                                       class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        <a asp-controller="Race" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a asp-controller="Race" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.RaceCategory</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <h2 class="display-4 fw-normal">Your Clubs</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            @foreach (var item in Model.Clubs)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.Image" width="100%" height="225" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Club" asp-action="Detail" asp-route-id="@item.Id"
                                       class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        <a asp-controller="Club" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a asp-controller="Club" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.clubCategory</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>

    </div>